apiVersion: v1
kind: Pod
metadata:
  name: test-pod1
spec:
  containers:
  - image: wangyanglinux/myapp:v1
    name: test-container
    volumeMounts:
    - mountPath: /cache    #挂在到容器内部的/cache目录下
      name: cache-volume   #以及通过哪个volume挂载的:cache-volume
  - name: test-redis
    image: redis:latest
    volumeMounts:
    - mountPath: /test    
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}