#在Azure AKS环境无法运行，必须在Node上预先创建好目录
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-hostpath
spec:
  containers:
  - image: wangyanglinux/myapp:v1
    name: test-container
    volumeMounts:
    - mountPath: /cache    #挂在到容器内部的/cache目录下
      name: cache-volume   #以及通过哪个volume挂载的:cache-volume
  volumes:
  - name: cache-volume
    hostPath:
      path: /data         #宿主机目录
      type: Directory     #挂载类型