apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myweb
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      nodeSelector:
        user: leizhang  #指定调度节点为带有label标记为：user: leizhang的node节点
      containers:
      - name: myweb
        image: wangyanglinux/nginx:v1.0
        ports:
        - containerPort: 80