apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod-volumn
spec:
  containers:
    - name: test-container
      image: wangyanglinux/myapp:v1
      command: [ "/bin/sh", "-c", "cat /etc/config/special.how" ]
      volumeMounts:  #cc
      - name: config-volume  
        mountPath: /etc/config  
  volumes:
    - name: config-volume   
      configMap:
        name: special-config
  restartPolicy: Never