apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    app: pod-2
spec:
  containers:
  - name: pod-2
    image: wangyanglinux/nginx:v1.0
  affinity:
    podAffinity:    #想要pod与指定pod运行在同一node上，官方说同一拓扑域
      requiredDuringSchedulingIgnoredDuringExecution:   #硬策略
      - labelSelector:
          matchExpressions:
          - key: app      #如果有app=node1  那么就在这个节点上创建pod-2
            operator: In
            values:
            - pod-1       #如果有app=node1  那么就在这个节点上创建pod-2
        topologyKey: kubernetes.io/hostname