apiVersion: v1
kind: PersistentVolume   #类型
metadata:
  name: pv0001
spec:
  capacity:            
    storage: 1Gi         #声明卷大小为5G
  volumeMode: Filesystem  
  accessModes:           
  - ReadWriteOnce    #只允许一个节点人读写
  persistentVolumeReclaimPolicy: Retain  #回收策略
  storageClassName: nfs                 #存储类名称 ，可以理解为，某些pv为一类，自然他也有命名空间，上头来请求的时候通过类名来区分
  nfs:
    path: /nfs/pv1                      #挂载到的目录
    server: 192.168.6.189               #nfs机器ip
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0002
spec:
  capacity:            
    storage: 2Gi
  volumeMode: Filesystem  
  accessModes:           
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /nfs/pv2
    server: 192.168.6.189
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
spec:
  capacity:            
    storage: 10Gi
  volumeMode: Filesystem  
  accessModes:           
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /nfs/pv3
    server: 192.168.6.189
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0004
spec:
  capacity:            
    storage: 5Gi
  volumeMode: Filesystem  
  accessModes:           
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-nginx
  nfs:
    path: /nfs/pv4
    server: 192.168.6.189